### ISSUE TITLE
Wallet does not start anymore

### ISSUE THREAD

**Issue by gradegal** [shane-kerr/MintCoin-Development-Updates#1]
Can anyone help me please ? Yesterday I synced my wallet after a few day of beeing offline.
It worked pretty good an I shut down the wallet at almost all blocks loaded.
Today I want to start the wallet again, but there is an error:

EXCEPTION: St9bad_alloc
std::bad_alloc
C:\Users\Papa\Desktop\MintCoin-Qt.exe in Runaway exception

what does this mean, what can I do ?

**Comment by EuroCentiem-dev** [comment]
Make a shortcut to Mintcoin-Qt.exe
Right click on the shortcut>Properties. Then add -splash=0 to the end of the target string.

**Comment by shane-kerr** [comment]
Thanks for the response @playtime1971.

In general I prefer for bug reports to be put on the wallet repository:

https://github.com/MintcoinCommunity/Mintcoin-Desktop-Wallet

I have created one here:

https://github.com/MintcoinCommunity/Mintcoin-Desktop-Wallet/issues/67
